# Moonfly — Kitty Color Theme
# Near-black background, soft grey text, violet accent

# Special
foreground              #bdbdbd
background              #080808
selection_foreground    #080808
selection_background    #b2ceee
cursor                  #9e9e9e
cursor_text_color       #080808
url_color               #80a0ff

# Tab bar
active_tab_foreground   #080808
active_tab_background   #ae81ff
inactive_tab_foreground #bdbdbd
inactive_tab_background #323437

# Borders
active_border_color     #ae81ff
inactive_border_color   #323437

# Marks
mark1_foreground        #080808
mark1_background        #ff5189
mark2_foreground        #080808
mark2_background        #80a0ff
mark3_foreground        #080808
mark3_background        #8cc85f

# Normal colors
# black
color0                  #323437
# red
color1                  #ff5454
# green
color2                  #8cc85f
# yellow
color3                  #e3c78a
# blue
color4                  #80a0ff
# magenta
color5                  #cf87e8
# cyan
color6                  #79dac8
# white
color7                  #c6c6c6

# Bright colors
# bright black
color8                  #949494
# bright red
color9                  #ff5189
# bright green
color10                 #36c692
# bright yellow
color11                 #c6c684
# bright blue
color12                 #74b2ff
# bright magenta
color13                 #ae81ff
# bright cyan
color14                 #85dc85
# bright white
color15                 #e4e4e4
